modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/187J3X1-114514/superresolution/issues"
license = "MIT"

[[mods]]
modId = "grapheneui"
version = "${version}"
displayName = "Graphene UI"
authors = "187J3X1"
description = '''
喵
'''
logoFile = "super_resolution_logo.png"

[[dependencies.grapheneui]]
modId = "minecraft"
mandatory = true
versionRange = "{versionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.grapheneui]]
modId = "architectury"
mandatory = true
versionRange = "[*,)"
ordering = "NONE"
side = "BOTH"

[mods."sodium:options"]
"mixin.features.render.gui.debug" = false

[[mixins]]
config = "grapheneui.mixins.json"