/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_homo_grapheneui_nanovg_NanoVGNative */

#ifndef _Included_io_homo_grapheneui_nanovg_NanoVGNative
#define _Included_io_homo_grapheneui_nanovg_NanoVGNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_homo_grapheneui_nanovg_NanoVGNative
 * Method:    unsafeCalloc
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_homo_grapheneui_nanovg_NanoVGNative_unsafeCalloc
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_homo_grapheneui_nanovg_NanoVGNative
 * Method:    unsafeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_homo_grapheneui_nanovg_NanoVGNative_unsafeFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
